"""
Terasploit Framework (c) 2026

Author:          4steroth
License:         BSD-3-Clause
Path:            teralibs/tsf/pex/terasm/terasm_const.py
"""

# terasm_const.py - Core constants for terasm.
# Derived from keystone_const.py; libkeystone.so is the underlying engine.

# API version (must match the libkeystone.so this module is linked against)
TA_API_MAJOR = 0
TA_API_MINOR = 9

# Library version
TA_VERSION_MAJOR = 0
TA_VERSION_MINOR = 9
TA_VERSION_EXTRA = 2

# Supported architectures
TA_ARCH_ARM = 1
TA_ARCH_ARM64 = 2
TA_ARCH_MIPS = 3
TA_ARCH_X86 = 4
TA_ARCH_PPC = 5
TA_ARCH_SPARC = 6
TA_ARCH_SYSTEMZ = 7
TA_ARCH_HEXAGON = 8
TA_ARCH_EVM = 9
TA_ARCH_MAX = 10

# Mode flags (combinable with bitwise OR where applicable)
TA_MODE_LITTLE_ENDIAN = 0
TA_MODE_BIG_ENDIAN = 1073741824

TA_MODE_ARM = 1
TA_MODE_THUMB = 16
TA_MODE_V8 = 64

TA_MODE_MICRO = 16
TA_MODE_MIPS3 = 32
TA_MODE_MIPS32R6 = 64
TA_MODE_MIPS32 = 4
TA_MODE_MIPS64 = 8

TA_MODE_16 = 2
TA_MODE_32 = 4
TA_MODE_64 = 8

TA_MODE_PPC32 = 4
TA_MODE_PPC64 = 8
TA_MODE_QPX = 16

TA_MODE_SPARC32 = 4
TA_MODE_SPARC64 = 8
TA_MODE_V9 = 16

# Error codes
TA_ERR_OK = 0
TA_ERR_NOMEM = 1
TA_ERR_ARCH = 2
TA_ERR_HANDLE = 3
TA_ERR_MODE = 4
TA_ERR_VERSION = 5
TA_ERR_OPT_INVALID = 6

# Assembly-level errors
TA_ERR_ASM = 128
TA_ERR_ASM_ARCH = 512
TA_ERR_ASM_EXPR_TOKEN = 128
TA_ERR_ASM_DIRECTIVE_VALUE_RANGE = 129
TA_ERR_ASM_DIRECTIVE_ID = 130
TA_ERR_ASM_DIRECTIVE_TOKEN = 131
TA_ERR_ASM_DIRECTIVE_STR = 132
TA_ERR_ASM_DIRECTIVE_COMMA = 133
TA_ERR_ASM_DIRECTIVE_RELOC_NAME = 134
TA_ERR_ASM_DIRECTIVE_RELOC_TOKEN = 135
TA_ERR_ASM_DIRECTIVE_FPOINT = 136
TA_ERR_ASM_DIRECTIVE_UNKNOWN = 137
TA_ERR_ASM_DIRECTIVE_EQU = 138
TA_ERR_ASM_DIRECTIVE_INVALID = 139
TA_ERR_ASM_VARIANT_INVALID = 140
TA_ERR_ASM_EXPR_BRACKET = 141
TA_ERR_ASM_SYMBOL_MODIFIER = 142
TA_ERR_ASM_SYMBOL_REDEFINED = 143
TA_ERR_ASM_SYMBOL_MISSING = 144
TA_ERR_ASM_RPAREN = 145
TA_ERR_ASM_STAT_TOKEN = 146
TA_ERR_ASM_UNSUPPORTED = 147
TA_ERR_ASM_MACRO_TOKEN = 148
TA_ERR_ASM_MACRO_PAREN = 149
TA_ERR_ASM_MACRO_EQU = 150
TA_ERR_ASM_MACRO_ARGS = 151
TA_ERR_ASM_MACRO_LEVELS_EXCEED = 152
TA_ERR_ASM_MACRO_STR = 153
TA_ERR_ASM_MACRO_INVALID = 154
TA_ERR_ASM_ESC_BACKSLASH = 155
TA_ERR_ASM_ESC_OCTAL = 156
TA_ERR_ASM_ESC_SEQUENCE = 157
TA_ERR_ASM_ESC_STR = 158
TA_ERR_ASM_TOKEN_INVALID = 159
TA_ERR_ASM_INSN_UNSUPPORTED = 160
TA_ERR_ASM_FIXUP_INVALID = 161
TA_ERR_ASM_LABEL_INVALID = 162
TA_ERR_ASM_FRAGMENT_INVALID = 163
TA_ERR_ASM_INVALIDOPERAND = 512
TA_ERR_ASM_MISSINGFEATURE = 513
TA_ERR_ASM_MNEMONICFAIL = 514

# Engine options
TA_OPT_SYNTAX = 1
TA_OPT_SYM_RESOLVER = 2

# Syntax styles (for TA_OPT_SYNTAX)
TA_OPT_SYNTAX_INTEL = 1
TA_OPT_SYNTAX_ATT = 2
TA_OPT_SYNTAX_NASM = 4
TA_OPT_SYNTAX_MASM = 8
TA_OPT_SYNTAX_GAS = 16
TA_OPT_SYNTAX_RADIX16 = 32
